In [1]:
import pandas as pd
import numpy as np

In [86]:
df = pd.read_csv('../data/iq_data.csv')
df['Entity'].unique()

array(['Africa', 'America', 'Argentina', 'Asia', 'Australia', 'Austria',
       'Belgium', 'Brazil', 'Bulgaria', 'Canada', 'China', 'Denmark',
       'Dominica', 'Estonia', 'Europe', 'Finland', 'France', 'Germany',
       'Global', 'Ireland', 'Israel', 'Japan', 'Kenya', 'Netherlands',
       'New Zealand', 'Norway', 'Oceania', 'Saudi Arabia', 'South Africa',
       'South Korea', 'Spain', 'Sudan', 'Sweden', 'Switzerland', 'Turkey',
       'United Kingdom', 'United States'], dtype=object)

In [62]:
read_file = pd.read_excel (r'../data/AHDI_countries.xlsx', sheet_name=2)
read_file.to_csv (r'../data/AHDI_countries.csv', index = None, header=True)
AHDI_df = pd.read_csv('../data/AHDI_countries.csv', index_col=0, skiprows =0)
AHDI_df

,1870,1880,1890,1900,1913,1925,1929,1933,1938,1950,...,1975,1980,1985,1990,1995,2000,2005,2007,2010,2015
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
Argentina,0.038852,0.042811,0.046814,0.056325,0.068095,0.092978,0.104660,0.118352,0.131428,0.164877,...,0.245418,0.263418,0.267702,0.270520,0.290246,0.301488,0.343744,0.340462,0.357299,0.394769
"Bahamas, The",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.210864,...,0.311470,0.341183,0.379532,0.404134,0.441377,0.482802,0.527112,0.495643,0.577474,0.476081
Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.182568,...,0.264070,0.287298,0.316659,0.335111,0.358790,0.349224,0.380097,0.353625,0.382429,0.441073
Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.242898,...,0.278807,0.265433,0.276717,0.323875,0.363835,0.411640,0.466567,0.508486,0.515876,0.442137
Bolivia,0.008219,0.013802,0.018892,0.032067,0.046336,0.072025,0.074370,0.072778,0.078827,0.090930,...,0.142518,0.169113,0.200523,0.233940,0.251810,0.265291,0.291580,0.267460,0.295838,0.292125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yemen,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,...,0.002470,0.005706,0.015331,0.030790,0.043586,0.062629,0.082400,0.054839,0.103942,0.082400
Australia,0.084251,0.119601,0.160213,0.199035,0.266445,0.278289,0.302046,0.320607,0.334075,0.367147,...,0.525533,0.588212,0.640268,0.697280,0.734329,0.742200,0.773166,0.591454,0.770840,0.777875
New Zealand,0.111522,0.130305,0.158318,0.199035,0.256944,0.261829,0.284614,0.297079,0.305408,0.322104,...,0.437700,0.439699,0.472456,0.489935,0.543789,0.609390,0.685290,0.534765,0.637348,0.662085
Canada,0.176921,0.196931,0.217643,0.236771,0.262415,0.297736,0.307666,0.323860,0.328041,0.347707,...,0.454166,0.507998,0.523121,0.619793,0.677081,0.715623,0.826438,0.645741,0.759116,0.763978
USA,0.171398,0.189454,0.214109,0.236304,0.253994,0.292371,0.306535,0.318004,0.329841,0.377949,...,0.542753,0.585799,0.632455,0.697280,0.752664,0.745893,0.795139,0.798664,0.878398,0.786637

In [67]:
# edit
north_america = ['USA', 'Canada', 'Mexico']
south_america = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela']
africa = ['Nigeria', 'Ethiopia', 'Egypt', 'DR Congo', 'Tanzania', 'South Africa',
    'Kenya', 'Uganda', 'Algeria', 'Sudan', 'Morocco', 'Angola', 'Mozambique',
    'Ghana', 'Madagascar', 'Cameroon', 'Côte d\'Ivoire', 'Niger', 'Burkina Faso',
    'Mali', 'Malawi', 'Zambia', 'Senegal', 'Chad', 'Somalia', 'Zimbabwe',
    'Guinea', 'Rwanda', 'Benin', 'Burundi', 'Tunisia', 'South Sudan', 'Togo',
    'Sierra Leone', 'Libya', 'Congo', 'Liberia', 'Central African Republic',
    'Mauritania', 'Eritrea', 'Namibia', 'Gambia', 'Botswana', 'Gabon',
    'Lesotho', 'Guinea-Bissau', 'Equatorial Guinea', 'Mauritius', 'Eswatini',
    'Djibouti', 'Comoros', 'Cabo Verde', 'Sao Tome & Principe', 'Seychelles'
]
africa = AHDI_df[AHDI_df.index.isin(africa)].index
asia = [ 
 'Afghanistan',
 'Armenia',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Bhutan',
 'Brunei',
 'Cambodia',
 'China',
 'Cyprus',
 'East Timor',
 'Egypt',
 'Georgia',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Israel',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Lebanon',
 'Malaysia',
 'Maldives',
 'Mongolia',
 'Myanmar',
 'Nepal',
 'North Korea',
 'Oman',
 'Pakistan',
 'Palestine',
 'Philippines',
 'Qatar',
 'Russia',
 'Saudi Arabia',
 'Singapore',
 'South Korea',
 'Sri Lanka',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Thailand',
 'Turkey',
 'Turkmenistan',
 'United Arab Emirates',
 'Uzbekistan',
 'Vietnam',
 'Yemen'
]

asia = AHDI_df[AHDI_df.index.isin(asia)].index
europe = [
 'Albania',
 'Andorra',
 'Armenia',
 'Austria',
 'Azerbaijan',
 'Belarus',
 'Belgium',
 'Bosnia and Herzegovina',
 'Bulgaria',
 'Croatia',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Georgia',
 'Germany',
 'Greece',
 'Hungary',
 'Iceland',
 'Ireland',
 'Italy',
 'Kazakhstan',
 'Latvia',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Malta',
 'Moldova',
 'Monaco',
 'Montenegro',
 'Netherlands',
 'Norway',
 'Poland',
 'Portugal',
 'Romania',
 'Russia',
 'San Marino',
 'Serbia',
 'Slovakia',
 'Slovenia',
 'Spain',
 'Sweden',
 'Switzerland',
 'Turkey',
 'Ukraine',
 'United Kingdom',
 'Vatican City'
]
europe = AHDI_df[AHDI_df.index.isin(europe)].index
oceania = ['Australia',
 'Federated States of Micronesia',
 'Fiji',
 'Kiribati',
 'Marshall Islands',
 'Nauru',
 'New Zealand',
 'Palau',
 'Papua New Guinea',
 'Samoa',
 'Solomon Islands',
 'Tonga',
 'Tuvalu',
 'Vanuatu'
]
oceania = AHDI_df[AHDI_df.index.isin(oceania)].index

,1870,1880,1890,1900,1913,1925,1929,1933,1938,1950,...,1975,1980,1985,1990,1995,2000,2005,2007,2010,2015
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
Australia,0.084251,0.119601,0.160213,0.199035,0.266445,0.278289,0.302046,0.320607,0.334075,0.367147,...,0.525533,0.588212,0.640268,0.697280,0.734329,0.74220,0.773166,0.591454,0.770840,0.777875
New Zealand,0.111522,0.130305,0.158318,0.199035,0.256944,0.261829,0.284614,0.297079,0.305408,0.322104,...,0.437700,0.439699,0.472456,0.489935,0.543789,0.60939,0.685290,0.534765,0.637348,0.662085

In [81]:
AHDI_df.columns = list(map( lambda x : int(x/10) * 10, AHDI_df.columns.astype('int')))
AHDI_df

,1870,1880,1890,1900,1910,1920,1920,1930,1930,1950,...,1970,1980,1980,1990,1990,2000,2000,2000,2010,2010
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
Argentina,0.038852,0.042811,0.046814,0.056325,0.068095,0.092978,0.104660,0.118352,0.131428,0.164877,...,0.245418,0.263418,0.267702,0.270520,0.290246,0.301488,0.343744,0.340462,0.357299,0.394769
"Bahamas, The",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.210864,...,0.311470,0.341183,0.379532,0.404134,0.441377,0.482802,0.527112,0.495643,0.577474,0.476081
Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.182568,...,0.264070,0.287298,0.316659,0.335111,0.358790,0.349224,0.380097,0.353625,0.382429,0.441073
Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.242898,...,0.278807,0.265433,0.276717,0.323875,0.363835,0.411640,0.466567,0.508486,0.515876,0.442137
Bolivia,0.008219,0.013802,0.018892,0.032067,0.046336,0.072025,0.074370,0.072778,0.078827,0.090930,...,0.142518,0.169113,0.200523,0.233940,0.251810,0.265291,0.291580,0.267460,0.295838,0.292125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yemen,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,0.002470,...,0.002470,0.005706,0.015331,0.030790,0.043586,0.062629,0.082400,0.054839,0.103942,0.082400
Australia,0.084251,0.119601,0.160213,0.199035,0.266445,0.278289,0.302046,0.320607,0.334075,0.367147,...,0.525533,0.588212,0.640268,0.697280,0.734329,0.742200,0.773166,0.591454,0.770840,0.777875
New Zealand,0.111522,0.130305,0.158318,0.199035,0.256944,0.261829,0.284614,0.297079,0.305408,0.322104,...,0.437700,0.439699,0.472456,0.489935,0.543789,0.609390,0.685290,0.534765,0.637348,0.662085
Canada,0.176921,0.196931,0.217643,0.236771,0.262415,0.297736,0.307666,0.323860,0.328041,0.347707,...,0.454166,0.507998,0.523121,0.619793,0.677081,0.715623,0.826438,0.645741,0.759116,0.763978
USA,0.171398,0.189454,0.214109,0.236304,0.253994,0.292371,0.306535,0.318004,0.329841,0.377949,...,0.542753,0.585799,0.632455,0.697280,0.752664,0.745893,0.795139,0.798664,0.878398,0.786637

In [113]:
df = pd.read_csv('../data/iq_data.csv')
df['Year'] = (df['Year'] // 10)
df['Year'].astype('int', )
df['Year'] = df['Year'] * 10

df.columns = ['Entity', 'Year', 'Average IQ Change', 'Fullscale IQ Change']

df = df[df['Fullscale IQ Change'].notnull()]
df.drop('Average IQ Change', inplace=True, axis=1)
df

     Entity  Year  Fullscale IQ Change
0    Africa  1960                 0.00
1    Africa  1960                 0.33
2    Africa  1980                 3.39
3    Africa  1980                 5.31
4    Africa  1990                10.83
5    Africa  2000                13.08
6   America  1900                 0.00
7   America  1920                 0.42
8   America  1930                12.90
9   America  1940                14.58
10  America  1970                27.78
11  America  2000                32.26
14     Asia  1950                 0.00
15     Asia  1950                 0.90
16     Asia  1960                10.74
17     Asia  1960                19.20
18     Asia  1980                28.05
19     Asia  2010                36.75
40   Europe  1910                 0.00
41   Europe  1930                 4.41
42   Europe  1940                 5.53
43   Europe  1950                10.37
44   Europe  1960                13.78
45   Europe  2010                22.80
52   Global  1900                 0.00
53   Global  1920                 1.12
54   Global  1930                 9.76
55   Global  1940                12.28
56   Global  1970                20.98
57   Global  2010                29.49
72  Oceania  1930                 0.00
73  Oceania  1940                 4.42
74  Oceania  1960                 9.46
75  Oceania  1980                17.86
76  Oceania  1990                19.87
77  Oceania  1990                20.31

In [123]:
AHDI_df.loc[europe, :].T
# european_mean = AHDI_df.loc[europe, :].T.apply(lambda x: x.mean(), axis = 0)

Unnamed: 0,Albania,Austria,Belgium,Belarus,Bulgaria,Croatia,Cyprus,Denmark,Estonia,Finland,...,Slovenia,Spain,Sweden,Switzerland,Ukraine,Armenia,Azerbaijan,Georgia,Kazakhstan,Turkey
1870,0.002470,0.088638,0.123708,NaN,0.043032,NaN,NaN,0.138452,NaN,0.037541,...,NaN,0.039071,0.122334,0.191516,NaN,NaN,NaN,NaN,NaN,0.006457
1880,0.002470,0.096067,0.142051,NaN,0.050295,NaN,NaN,0.147517,NaN,0.039728,...,NaN,0.053981,0.135598,0.213670,NaN,NaN,NaN,NaN,NaN,0.008215
1890,0.002470,0.112522,0.156057,NaN,0.059145,NaN,NaN,0.159075,NaN,0.042203,...,NaN,0.071306,0.150465,0.227995,NaN,NaN,NaN,NaN,NaN,0.009728
1900,0.002470,0.136203,0.156057,NaN,0.073883,NaN,NaN,0.172968,NaN,0.045252,...,NaN,0.086111,0.168278,0.245761,NaN,NaN,NaN,NaN,NaN,0.011756
1910,0.004685,0.185527,0.171398,NaN,0.100048,NaN,0.048411,0.202427,NaN,0.073582,...,NaN,0.104137,0.198613,0.266445,NaN,NaN,NaN,NaN,NaN,0.014818
1920,0.012065,0.186569,0.179897,NaN,0.114459,NaN,0.064061,0.206344,NaN,0.085959,...,NaN,0.105511,0.206914,0.283990,NaN,NaN,NaN,NaN,NaN,0.016128
1920,0.015933,0.183579,0.184146,NaN,0.119941,NaN,0.078014,0.214989,NaN,0.102639,...,NaN,0.106889,0.211918,0.297610,NaN,NaN,NaN,NaN,NaN,0.016359
1930,0.020088,0.192905,0.185259,NaN,0.139432,NaN,0.089713,0.221884,NaN,0.120857,...,NaN,0.115520,0.216685,0.312512,NaN,NaN,NaN,NaN,NaN,0.018946
1930,0.026034,0.198613,0.195256,NaN,0.151577,NaN,0.099910,0.228909,NaN,0.148252,...,NaN,0.134179,0.225266,0.328041,NaN,NaN,NaN,NaN,NaN,0.020759
1950,0.070292,0.223008,0.212355,NaN,0.179314,NaN,0.124785,0.261414,NaN,0.187813,...,NaN,0.146417,0.250096,0.363835,NaN,NaN,NaN,NaN,NaN,0.030790
1950,0.075389,0.250239,0.230374,NaN,0.214587,NaN,0.137681,0.288203,NaN,0.203808,...,NaN,0.158507,0.270557,0.381949,NaN,NaN,NaN,NaN,NaN,0.042215
1960,0.081785,0.274640,0.244327,NaN,0.248646,NaN,0.159276,0.329240,NaN,0.229825,...,NaN,0.171007,0.308233,0.407906,NaN,NaN,NaN,NaN,NaN,0.057704
1960,0.095237,0.304564,0.260167,NaN,0.263548,NaN,0.173469,0.353356,NaN,0.241306,...,NaN,0.190083,0.341361,0.462009,NaN,NaN,NaN,NaN,NaN,0.070991
1970,0.124052,0.337129,0.276717,NaN,0.284614,NaN,0.185742,0.394052,NaN,0.262916,...,NaN,0.205850,0.384864,0.506055,NaN,NaN,NaN,NaN,NaN,0.086734
1970,0.162882,0.371497,0.300002,NaN,0.313219,NaN,0.200773,0.430502,NaN,0.305660,...,NaN,0.221766,0.427901,0.549133,NaN,NaN,NaN,NaN,NaN,0.100912
1980,0.204991,0.409395,0.337129,0.296653,0.337743,0.283551,0.217276,0.470947,0.314463,0.367147,...,0.342692,0.248163,0.486242,0.610675,0.304461,0.369642,0.336877,0.364732,0.321891,0.122334
1980,0.270008,0.433051,0.364345,0.332746,0.353629,0.305408,0.241484,0.503130,0.352410,0.410657,...,0.410890,0.275937,0.527504,0.661146,0.352264,0.409779,0.388620,0.403049,0.367136,0.153200
1990,0.308801,0.467439,0.401279,0.372752,0.377265,0.312799,0.257138,0.526990,0.389521,0.451214,...,0.467439,0.305971,0.573962,0.702193,0.384632,0.443116,0.448813,0.445807,0.403735,0.160593
1990,0.293227,0.488546,0.435512,0.383932,0.413898,0.343315,0.283582,0.566349,0.452901,0.495285,...,0.492729,0.333543,0.539663,0.690830,0.441104,0.448892,0.452076,0.452314,0.441712,0.175534
2000,0.369148,0.510933,0.463963,0.395461,0.454571,0.384864,0.306351,0.596786,0.512962,0.534241,...,0.521897,0.370489,0.540572,0.679806,0.477015,0.453057,0.455368,0.458938,0.483026,0.201151
2000,0.394769,0.518729,0.498938,0.459649,0.483497,0.451214,0.283694,0.641797,0.523700,0.564759,...,0.547013,0.396926,0.558004,0.695054,0.524039,0.454907,0.462759,0.468899,0.517320,0.206314
2000,0.426486,0.380282,0.450180,0.356652,0.389608,0.488084,0.362258,0.522910,0.587429,0.422428,...,0.585198,0.405566,0.558104,0.415470,0.505272,0.469263,0.421604,0.608110,0.545931,0.197520
2010,0.400550,0.537393,0.515876,0.537393,0.514882,0.516873,0.387808,0.603035,0.532742,0.598027,...,0.581019,0.425403,0.576299,0.694041,0.538610,0.471650,0.470300,0.479136,0.564530,0.220763
2010,0.380479,0.520279,0.525042,0.591473,0.469962,0.509188,0.558588,0.692459,0.668718,0.506442,...,0.609639,0.390547,0.629643,0.819582,0.520887,0.515981,0.503158,0.625978,0.556445,0.275566

In [121]:
european_mean

Unnamed: 0
Albania        0.156116
Austria        0.308656
Belgium        0.292085
Belarus        0.414079
Bulgaria       0.256283
Croatia        0.399477
Cyprus         0.213001
Denmark        0.369739
Estonia        0.481650
Finland        0.269898
France         0.374466
Germany        0.461220
Greece         0.219318
Hungary        0.280127
Iceland        0.339493
Ireland        0.292792
Italy          0.222479
Latvia         0.435293
Lithuania      0.443709
Malta          0.281244
Moldova        0.384059
Netherlands    0.330060
Norway         0.398915
Poland         0.184877
Portugal       0.128385
Romania        0.220565
Russia         0.244055
Slovenia       0.506502
Spain          0.210953
Sweden         0.358712
Switzerland    0.458634
Ukraine        0.449809
Armenia        0.448476
Azerbaijan     0.437731
Georgia        0.478552
Kazakhstan     0.466858
Turkey         0.092729
dtype: float64

3.44